#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 09 Production RAG — One-shot Caddy HTTPS reverse proxy setup
# ============================================================
#
# Usage:
#   sudo bash setup_caddy.sh <your-domain>
#
# Example:
#   sudo bash setup_caddy.sh your-domain.com
#
# This script:
#   1. Installs Caddy if not present
#   2. Configures Caddy to reverse-proxy the domain to localhost:8080
#   3. Enables automatic Let's Encrypt TLS
#   4. Opens ports 80/443 in ufw (if ufw is active)
#   5. Starts and enables Caddy
#
# After running, visit https://<your-domain> — Caddy handles TLS automatically.

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[x]${NC} $*"; exit 1; }

# ── Parse args ──────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <domain>"
  echo "Example: $0 your-domain.com"
  exit 1
fi

DOMAIN="$1"

if [[ ! "$DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$ ]]; then
  err "Invalid domain: $DOMAIN"
fi

log "Setting up Caddy reverse proxy for https://${DOMAIN} → http://localhost:8080"

# ── Check we're root ────────────────────────────────────────
if [[ "$(id -u)" -ne 0 ]]; then
  err "This script must be run as root (sudo). It installs packages and writes system configs."
fi

# ── Ensure the web container is reachable ───────────────────
if ! curl -s -o /dev/null -w '' http://localhost:8080/; then
  warn "localhost:8080 is not responding. Make sure 'docker compose up -d' has been run."
  read -rp "Continue anyway? [y/N] " answer
  [[ "$answer" =~ ^[Yy]$ ]] || exit 0
fi

# ── Install Caddy ──────────────────────────────────────────
if ! command -v caddy &>/dev/null; then
  log "Installing Caddy..."
  if command -v apt-get &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
      | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
      | tee /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq
    apt-get install -y -qq caddy
  elif command -v dnf &>/dev/null; then
    dnf install -y 'dnf-command(copr)'
    dnf copr enable -y @caddy/caddy
    dnf install -y caddy
  elif command -v yum &>/dev/null; then
    yum install -y yum-plugin-copr
    yum copr enable -y @caddy/caddy
    yum install -y caddy
  else
    err "Unsupported package manager. Install Caddy manually: https://caddyserver.com/docs/install"
  fi
  log "Caddy installed: $(caddy version | head -1)"
else
  log "Caddy is already installed: $(caddy version | head -1)"
fi

# ── Write Caddyfile ─────────────────────────────────────────
CADDYFILE="/etc/caddy/Caddyfile"

if [[ -f "$CADDYFILE" ]]; then
  BACKUP="${CADDYFILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$CADDYFILE" "$BACKUP"
  log "Existing Caddyfile backed up to $BACKUP"
fi

cat > "$CADDYFILE" <<EOF
# Generated by setup_caddy.sh for 09 Production RAG
# https://caddyserver.com/docs/caddyfile

${DOMAIN} {
    reverse_proxy localhost:8080
}
EOF

log "Caddyfile written: $CADDYFILE"

# ── Validate config ─────────────────────────────────────────
if caddy validate --config "$CADDYFILE" 2>&1; then
  log "Caddyfile syntax is valid."
else
  warn "Caddyfile validation failed. Check $CADDYFILE manually."
fi

# ── Open firewall ports ─────────────────────────────────────
if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
  log "Opening ports 80/tcp and 443/tcp in ufw..."
  ufw allow 80/tcp  || true
  ufw allow 443/tcp || true
fi

# ── Start & enable Caddy ────────────────────────────────────
log "Starting Caddy..."
systemctl enable caddy --now

# ── Verify ──────────────────────────────────────────────────
sleep 2
if systemctl is-active --quiet caddy; then
  log "Caddy is running (systemctl status caddy)."
else
  warn "Caddy did not start. Check: journalctl -u caddy --no-pager -n 30"
fi

echo
log "Done! Visit https://${DOMAIN}"
echo
echo "Notes:"
echo "  - TLS certificate is issued automatically via Let's Encrypt."
echo "  - It may take up to 30 seconds for the first certificate to be obtained."
echo "  - Caddy auto-renews certificates; no maintenance needed."
echo "  - Logs: journalctl -u caddy -f"
echo "  - Config: ${CADDYFILE}"
